name: Java CI with Maven

# 이벤트 처리 => master 브랜치에서 push가 된 경우
on:
  push:
    branches: [ "master" ]

# CI/CD 작업
jobs:
  deploy:
    runs-on: self-hosted
  # 모든 명령의 기본 작업 디렉토리 설정
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maven Build
        run: mvn clean package -DskipTests

      - name: Stop Tomcat
        run: |
          sudo /home/sist/apache-tomcat-9.0.120/bin/shutdown.sh || true
          sleep 3

      - name: Remove Old war
        run: |
          sudo rm -rf /home/sist/apache-tomcat-9.0.120/webapps/SpringLastProject.war
          sudo rm -rf /home/sist/apache-tomcat-9.0.120/webapps/SpringLastProject

      - name: Deploy War
        run: |
          sudo cp target/*.war /home/sist/apache-tomcat-9.0.120/webapps/SpringLastProject.war 
      - name: Tomcat Start
        run: |
          sudo nohup /home/sist/apache-tomcat-9.0.120/bin/startup.sh
          sleep 5

